version: '3.9'

services:
  mongo_db:
    container_name: mongodb_container
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: {}