export const genres = [
    'Action and Adventure',
    'Art',
    'Biographies',
    "Children's",
    'Comics',
    'Cookbooks',
    'Crime',
    'Drama',
    'Fantasy',
    'Graphic Novels',
    'Historical Fiction',
    'History',
    'Horror',
    'Humor and Comedy',
    'Mystery',
    'Poetry',
    'Religion and Spirituality',
    'Romance',
    'Science',
    'Science Fiction',
    'Self-help',
    'Suspense and Thriller',
    'Travel',
];
